### ISSUE TITLE
Finish Landing Page

### ISSUE THREAD

**Issue by michaelsong4399** [hack-duke/2023.hackduke.org#2]

**Comment by jamesxu123** [comment]
Things for us to fix:

- [ ] Add a "sign up for mailing list" button - can just copy the mailing list link from the current website
- [ ] Have the website be 100vh so no scrolling (might need to make the header menu at the top transparent (could do a frosted glass effect)
- [ ] The "code for good" text looks really pixelated? Can we try and fix this when exporting from Figma?
- [ ] Add relevant social media buttons

**Comment by michaelsong4399** [comment]
Fix buttons please they look bad and design is clowning me
